SELECT NAME, usersTable.USER_ID, COALESCE(
(SELECT COUNT(*) FROM `meh`.PHOTO_POST
	JOIN `meh`.USER ON USER.USER_ID = PHOTO_POST.USER_ID
	WHERE DAY(PHOTO_POST.CREATION_DATE) = 9
			AND MONTH(PHOTO_POST.CREATION_DATE) = 5
			AND PHOTO_POST.USER_ID = usersTable.USER_ID ), 0) as 'Count'
	FROM `meh`.PHOTO_POST
	RIGHT JOIN `meh`.USER as usersTable ON usersTable.USER_ID = PHOTO_POST.USER_ID
	GROUP BY usersTable.USER_ID