SELECT USER.NAME FROM `meh`.USER
	JOIN `meh`.PHOTO_POST ON USER.USER_ID = PHOTO_POST.USER_ID
	WHERE DATE(PHOTO_POST.CREATION_DATE) = DATE(NOW()) GROUP BY USER.NAME
    HAVING COUNT(PHOTO_POST.POST_ID) > 3