-- MySQL Script generated by MySQL Workbench
-- Tue May  7 13:07:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema meh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema meh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meh` DEFAULT CHARACTER SET utf8 ;
USE `meh` ;

-- -----------------------------------------------------
-- Table `meh`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meh`.`USER` (
  `USER_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meh`.`PHOTO_POST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meh`.`PHOTO_POST` (
  `POST_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(45) NOT NULL,
  `CREATION_DATE` VARCHAR(45) NOT NULL,
  `PHOTO_LINK` VARCHAR(45) NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`POST_ID`),
  INDEX `fk_PHOTO_POST_USER_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PHOTO_POST_USER`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `meh`.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `meh`.`USER`
-- -----------------------------------------------------
START TRANSACTION;
USE `meh`;
INSERT INTO `meh`.`USER` (`USER_ID`, `NAME`) VALUES (10, 'gleb');
INSERT INTO `meh`.`USER` (`USER_ID`, `NAME`) VALUES (11, 'hleb');
INSERT INTO `meh`.`USER` (`USER_ID`, `NAME`) VALUES (21, 'glebushek');
INSERT INTO `meh`.`USER` (`USER_ID`, `NAME`) VALUES (31, 'dva');
INSERT INTO `meh`.`USER` (`USER_ID`, `NAME`) VALUES (41, 'tri');
INSERT INTO `meh`.`USER` (`USER_ID`, `NAME`) VALUES (51, 'sem');
INSERT INTO `meh`.`USER` (`USER_ID`, `NAME`) VALUES (61, 'fatos');
INSERT INTO `meh`.`USER` (`USER_ID`, `NAME`) VALUES (71, 'egor');
INSERT INTO `meh`.`USER` (`USER_ID`, `NAME`) VALUES (81, 'meh');
INSERT INTO `meh`.`USER` (`USER_ID`, `NAME`) VALUES (91, 'patrick');
INSERT INTO `meh`.`USER` (`USER_ID`, `NAME`) VALUES (101, 'spange bob');

COMMIT;


-- -----------------------------------------------------
-- Data for table `meh`.`PHOTO_POST`
-- -----------------------------------------------------
START TRANSACTION;
USE `meh`;
INSERT INTO `meh`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (1, 'DESC1', '11.12.10', '1.jpg', 11);
INSERT INTO `meh`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (2, 'DESC2', '11.12.16', '2.jpg', 21);
INSERT INTO `meh`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (3, 'DESC3', '11.12.19', '3.jpg', 31);
INSERT INTO `meh`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (4, 'DESC4', '11.12.19', '4.jpg', 41);
INSERT INTO `meh`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (5, 'DESC5', '11.12.17', '5.jpg', 51);
INSERT INTO `meh`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (6, 'DESC6', '11.12.19', '6.jpg', 61);
INSERT INTO `meh`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (7, 'DESC7', '11.12.18', '7.jpg', 71);
INSERT INTO `meh`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (8, 'DESC8', '11.12.19', '8.jpg', 81);
INSERT INTO `meh`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (9, 'DESC9', '11.12.13', '9.jpg', 91);
INSERT INTO `meh`.`PHOTO_POST` (`POST_ID`, `DESCRIPTION`, `CREATION_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (10, 'DESC10', '11.12.19', '10.jpg', 101);

COMMIT;

